### ISSUE TITLE
get java.lang.ClassCastExceptio

### ISSUE THREAD

**Issue by xprojects-de** [xprojects-de/alpdesk-automationservice#12]
After Exception Application dies

2020-09-06 12:55:29.234  INFO 433 --- [nio-5005-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/java.io.DataInputStream.read(DataInputStream.java:149)
	at net.wimpi.modbus.io.ModbusTCPTransport.readResponse(ModbusTCPTransport.java:171)
	at net.wimpi.modbus.io.ModbusTCPTransaction.execute(ModbusTCPTransaction.java:193)
	at net.wimpi.modbus.facade.ModbusTCPMaster.readInputDiscretes(ModbusTCPMaster.java:219)
	at x.modbus.XModbusMaster.readModbusDigitalInputs(XModbusMaster.java:157)
	at x.modbus.XModbusMaster.start(XModbusMaster.java:96)
	at x.main.XHomeautomationMain$1.run(XHomeautomationMain.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "Thread-169" java.lang.ClassCastException: class net.wimpi.modbus.msg.ReadInputDiscretesResponse cannot be cast to class net.wimpi.modbus.msg.ReadCoilsResponse (net.wimpi.modbus.msg.ReadInputDiscretesResponse and net.wimpi.modbus.msg.ReadCoilsResponse are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @e048a)
	at net.wimpi.modbus.facade.ModbusTCPMaster.readCoils(ModbusTCPMaster.java:157)
	at x.modbus.XModbusMaster.writeModbusDigitalOutputs(XModbusMaster.java:179)
	at x.modbus.XModbusMaster.start(XModbusMaster.java:103)
	at x.main.XHomeautomationMain$1.run(XHomeautomationMain.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by xprojects-de** [comment]
should be solved in 2.2.5 because ModbusRead/ModbusWrite catches Exception instead of ModbusException.

Interpreting the response for ReadCoils is wrong FunctionCode. Instead of FC1, FC2 as RdadInputDiscrete is comming and that´s the reason for the Cast-Error.
Maybe the Coupler or the NetworkConnection does have problems!

**Comment by xprojects-de** [comment]
[XHomeautomationLog.log](https://github.com/xprojects-de/alpdesk-automationservice/files/5434154/XHomeautomationLog.log)
